#spring.data.mongodb.uri=mongodb+srv://nidvmehta22_db_user:ehilhLpuaUe1lWws@cluster0.p42j5wn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
